# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0a6e3ca2eee88faf3da8bd770e74390ef6c8cbc792a72879afb36cad10e2c1f92ae3716f204f3d472c8623696951e21d5ebee0c8a5226f7e62fd53aace12e2a

test:
  secret_key_base: b320e204bb00111a630822428f004863d5719d5610e08e1c06183db437c469f42d5f9c437a2587e7aa37940bb15168b888f5b70cfe1b4d880dba3361401b395b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
